### ISSUE TITLE
Cache sensor data to avoid JSON errors from PurpleAir

### ISSUE THREAD

**Issue by jasonsnell** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#20]
I've just created a new branch, cache-sensor-data, with a proposed change that caches data every time we have a successful sensor load, and then reads that data and returns it when there's a JSON parse error. 

Would be fantastic if someone who knows anything were to check my work! But in a brief test here it seemed to... do what it was supposed to?

**Comment by lickel** [comment]
It looks reasonable, but you might want to do something like:

```
const sensorData = { json, updatedAt: Date.now() }
cacheData("sensordata.json", sensorData);
// ...
const { json, updatedAt } = getCachedData(`sensordata.json`)
```

> A note on the syntactic sugar there:
> `{ json }` gets inflated as `{ json: <value of json> }`.

Why you might want to store `updatedAt`: if this is really old, we can still throw 666.
Then it'll be super obvious that something has gone wrong (instead of the tiny updated text row).

---

In order to repeat yourself less, you could also restructure it a bit:

```
let json = await req.loadJSON();

try {
  // Check that our results are what we expect
  if (json && json.results && Array.isArray(json.results) && json.results.length > 1) {
    console.log(`Sensor data looks good, will cache.`);
    const sensorData = { json, updatedAt: Date.now() }
    cacheData("sensordata.json", sensorData);
  } else {
    const { json: cachedJson, updatedAt } = getCachedData(`sensordata.json`);
    if (Date.now() - updatedAt > 2 * 60 * 60 * 1000) {
      // Bail if our data is > 2 hours old
      throw `Our cache is too old: ${updatedAt }`;
    }
    console.log(`Using cached sensor data: ${updatedAt}`);
    json = cachedJson;
  }
  return {
    val: json.results[0].Stats,
    adj1: json.results[0].pm2_5_cf_1,
    adj2: json.results[1].pm2_5_cf_1,
    ts: json.results[0].LastSeen,
    hum: json.results[0].humidity,
    loc: json.results[0].Label,
    lat: json.results[0].Lat,
    lon: json.results[0].Lon,
  };
} catch(error) {
  console.log(`Could not parse JSON: ${error}`);
  throw 666;
}
```

The data checking is a _little_ more robust (`json.results[1]` will exist), and the method will always either return our expected results or throw a 666 (bringing us back to that new error design).
It also lets us tweak how long we trust the cached data.

**Comment by lickel** [comment]
My guess would be that the only reason you'd keep getting a failure is if the sensor gets shut down, but, who knows 🙂
