### ISSUE TITLE
Adapt/fork to use EPA data?

### ISSUE THREAD

**Issue by nmatthews** [jasonsnell/PurpleAir-AQI-Scriptable-Widget#4]
Thanks so much for building this. I'd love to have a version of it that uses EPA's data reported with its more sophisticated sensors, albeit with a long time delay. https://docs.airnowapi.org/Data/docs. I don't know whether everyone would need to enter their own API key, although I found signing up for one to be painless (took less than a minute). I haven't figured out how to use the AirNow API to directly name a monitor, rather than to draw a box with GPS coordinates, but once you know where the monitors are it's easy to draw a box around the one you want.

**Comment by jasonsnell** [comment]
Hi @nmatthews -- TBH there are lots of commercial apps that integrate the AirNow API, since it's the gold standard, and many of them have widgets. The point of this widget was to use the smaller network to provide better hyperlocal results. My nearest AirNow sensor is a couple of towns over and in heavy smoke conditions it doesn't properly reflect my area, nor does it respond quickly enough to changes in air quality.

So you're welcome to fork this project but honestly I think you'd just be better off using any weather app that supports air quality, because it will probably be providing you with the same data.
